version: "3.9"

services:
    postgres:
        image: postgres:16.2
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
volumes:
    db:
        driver: local
